In [13]:
from path import Path
import pandas as pd
from sklearn.linear_model import LogisticRegression

In [14]:
data = Path('../Group3/Group3Dataset.csv')
df = pd.read_csv(data)
df.head()

,Unnamed: 0,origin,destination,price,airline,flight_number,departure_at,transfers,Average Temperature (Farenheit),Population
0,5/4/23,PHX,NYC,518,AS,763,2023-05-04T16:40:00-07:00,1,53.4,"8,804,190"
1,5/5/23,PHX,NYC,518,AS,763,2023-05-05T16:40:00-07:00,1,53.4,"8,804,190"
2,5/6/23,PHX,NYC,419,AS,611,2023-05-06T18:50:00-07:00,1,53.4,"8,804,190"
3,5/7/23,PHX,NYC,437,DL,673,2023-05-06T23:15:00-07:00,0,53.4,"8,804,190"
4,5/8/23,PHX,NYC,447,NaN,4020,2023-05-07T18:13:00-07:00,1,53.4,"8,804,190"

In [15]:
df.dtypes

Unnamed: 0                          object
origin                              object
destination                         object
price                                int64
airline                             object
flight_number                        int64
departure_at                        object
transfers                            int64
Average Temperature (Farenheit)    float64
Population                          object
dtype: object

In [16]:
# Change object to int
df['Population'] = df['Population'].str.replace(',', '').astype(int)

In [17]:
df.dtypes

Unnamed: 0                          object
origin                              object
destination                         object
price                                int64
airline                             object
flight_number                        int64
departure_at                        object
transfers                            int64
Average Temperature (Farenheit)    float64
Population                           int64
dtype: object

In [25]:
# Define variable and target
X = df[['Population','transfers', 'Average Temperature (Farenheit)']].values # independent variable
y = df['price'].values # target variable

In [26]:
#Split for training and testing
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [27]:
# Create Logistic Regression Model
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(solver='lbfgs',
                                max_iter=200,
                                random_state=1)

In [28]:
# Fit the model
classifier.fit(X_train, y_train)

LogisticRegression(max_iter=200, random_state=1)

In [29]:
y_pred = classifier.predict(X_test)
results = pd.DataFrame({"Prediction": y_pred, "Actual": y_test}).reset_index(drop=True)
results.head(20)

    Prediction  Actual
0          317     197
1          317     416
2          317     147
3          317     277
4          317     286
5          317    2275
6          317     464
7          317     240
8          317     287
9          317      67
10         317     147
11         317     277
12         317     617
13         317      66
14         317     317
15         317      67
16         317     835
17         317     287
18         317     277
19         317     157

In [30]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, y_pred))

0.01556420233463035

In [31]:
from sklearn.metrics import confusion_matrix, classification_report
matrix = confusion_matrix(y_test, y_pred)
print(matrix)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]

In [32]:
report = classification_report(y_test, y_pred)
print(report)

              precision    recall  f1-score   support

          47       0.00      0.00      0.00         3
          66       0.00      0.00      0.00         2
          67       0.00      0.00      0.00        16
          72       0.00      0.00      0.00         2
          76       0.00      0.00      0.00         2
          77       0.00      0.00      0.00        10
          78       0.00      0.00      0.00         1
          82       0.00      0.00      0.00         2
          86       0.00      0.00      0.00         1
          87       0.00      0.00      0.00         5
          92       0.00      0.00      0.00         2
          97       0.00      0.00      0.00         3
          98       0.00      0.00      0.00         1
          99       0.00      0.00      0.00         1
         102       0.00      0.00      0.00         1
         109       0.00      0.00      0.00         2
         115       0.00      0.00      0.00         1
         117       0.00      0.00      0.00         2
         127       0.00      0.00      0.00         3
         133       0.00      0.00      0.00         2
         141       0.00      0.00      0.00         1
         142       0.00      0.00      0.00         1
         146       0.00      0.00      0.00         1
         147       0.00      0.00      0.00         5
         157       0.00      0.00      0.00         6
         159       0.00      0.00      0.00         1
         176       0.00      0.00      0.00         1
         177       0.00      0.00      0.00         4
         178       0.00      0.00      0.00         1
         182       0.00      0.00      0.00         1
         187       0.00      0.00      0.00         1
         188       0.00      0.00      0.00         1
         191       0.00      0.00      0.00         1
         196       0.00      0.00      0.00         1
         197       0.00      0.00      0.00         1
         198       0.00      0.00      0.00         1
         202       0.00      0.00      0.00         2
         207       0.00      0.00      0.00         1
         212       0.00      0.00      0.00         1
         217       0.00      0.00      0.00         1
         218       0.00      0.00      0.00         2
         225       0.00      0.00      0.00         1
         228       0.00      0.00      0.00         2
         230       0.00      0.00      0.00         2
         232       0.00      0.00      0.00         1
         233       0.00      0.00      0.00         4
         236       0.00      0.00      0.00         1
         240       0.00      0.00      0.00         2
         246       0.00      0.00      0.00         1
         248       0.00      0.00      0.00         1
         253       0.00      0.00      0.00         1
         256       0.00      0.00      0.00         2
         259       0.00      0.00      0.00         1
         261       0.00      0.00      0.00         1
         263       0.00      0.00      0.00         1
         267       0.00      0.00      0.00         3
         270       0.00      0.00      0.00         1
         271       0.00      0.00      0.00         3
         272       0.00      0.00      0.00         1
         276       0.00      0.00      0.00         1
         277       0.00      0.00      0.00         6
         278       0.00      0.00      0.00         1
         280       0.00      0.00      0.00         1
         286       0.00      0.00      0.00         2
         287       0.00      0.00      0.00         6
         289       0.00      0.00      0.00         5
         290       0.00      0.00      0.00         2
         292       0.00      0.00      0.00         1
         296       0.00      0.00      0.00         1
         297       0.00      0.00      0.00         5
         302       0.00      0.00      0.00         1
         303       0.00      0.00      0.00         1
         304       0.00      0.00      0.00         3
         307       0.00      0.00      0.00         3
         309       0.00      0.00      0.00         1
         311       0.00      0.00      0.00         1
         312       0.00      0.00      0.00         1
         317       0.02      1.00      0.03         4
         322       0.00      0.00      0.00         4
         323       0.00      0.00      0.00         1
         326       0.00      0.00      0.00         1
         327       0.00      0.00      0.00         2
         330       0.00      0.00      0.00         1
         332       0.00      0.00      0.00         1
         336       0.00      0.00      0.00         1
         337       0.00      0.00      0.00         1
         355       0.00      0.00      0.00         4
         356       0.00      0.00      0.00         2
         357       0.00      0.00      0.00         2
         358       0.00      0.00      0.00         1
         364       0.00      0.00      0.00         1
         367       0.00      0.00      0.00         1
         372       0.00      0.00      0.00         1
         377       0.00      0.00      0.00         2
         378       0.00      0.00      0.00         2
         387       0.00      0.00      0.00         2
         390       0.00      0.00      0.00         1
         397       0.00      0.00      0.00         1
         400       0.00      0.00      0.00         2
         407       0.00      0.00      0.00         1
         411       0.00      0.00      0.00         1
         416       0.00      0.00      0.00         3
         418       0.00      0.00      0.00         2
         426       0.00      0.00      0.00         1
         429       0.00      0.00      0.00         1
         430       0.00      0.00      0.00         1
         436       0.00      0.00      0.00         1
         438       0.00      0.00      0.00         3
         440       0.00      0.00      0.00         2
         442       0.00      0.00      0.00         1
         448       0.00      0.00      0.00         1
         451       0.00      0.00      0.00         1
         453       0.00      0.00      0.00         1
         456       0.00      0.00      0.00         1
         457       0.00      0.00      0.00         1
         460       0.00      0.00      0.00         1
         464       0.00      0.00      0.00         1
         468       0.00      0.00      0.00         1
         469       0.00      0.00      0.00         1
         476       0.00      0.00      0.00         1
         480       0.00      0.00      0.00         1
         484       0.00      0.00      0.00         1
         497       0.00      0.00      0.00         1
         498       0.00      0.00      0.00         1
         502       0.00      0.00      0.00         1
         507       0.00      0.00      0.00         1
         518       0.00      0.00      0.00         1
         522       0.00      0.00      0.00         1
         524       0.00      0.00      0.00         1
         537       0.00      0.00      0.00         2
         547       0.00      0.00      0.00         1
         556       0.00      0.00      0.00         1
         562       0.00      0.00      0.00         1
         565       0.00      0.00      0.00         1
         600       0.00      0.00      0.00         1
         617       0.00      0.00      0.00         1
         620       0.00      0.00      0.00         1
         622       0.00      0.00      0.00         1
         660       0.00      0.00      0.00         1
         742       0.00      0.00      0.00         1
         835       0.00      0.00      0.00         1
        2275       0.00      0.00      0.00         2

    accuracy                           0.02       257
   macro avg       0.00      0.01      0.00       257
weighted avg       0.00      0.02      0.00       257

/Users/zachkriegs/opt/anaconda3/envs/mlenv/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/zachkriegs/opt/anaconda3/envs/mlenv/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/zachkriegs/opt/anaconda3/envs/mlenv/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))